### ISSUE TITLE
Indexing succeeds, searching give no results

### ISSUE THREAD

**Issue by rvreugde** [trilbymedia/grav-plugin-tntsearch#109]
Hello,

I am using the TNTSearch plugin (v3.3.0) with my Grav site (v1.6.30) but I encounter a problem.
The site is running on Apache/PHP on a CentOS 8.2 server.

Indexing succeeds, without a (visible) problem (via admin page or cli):
![image](https://user-images.githubusercontent.com/38208623/102071149-5f9d5280-3e00-11eb-8b4b-1993affc990f.png)

But, when I want to search, it gives no result!
![image](https://user-images.githubusercontent.com/38208623/102071297-8eb3c400-3e00-11eb-8366-3d47ca605853.png)

Can somebody help?

Regards,
Raf

**Comment by janousek** [comment]
Maybe related to https://github.com/trilbymedia/grav-plugin-tntsearch/issues/107

**Comment by jraack** [comment]
Hi, i am still facing this issue. Grav is running with the officiel grav docker image, somehow it gives 0 results; tntsearch index via cli works. Any ideas?

**Comment by rhukster** [comment]
Can someone provide a zip of a test site so we can try to reproduce this?

**Comment by AquaL1te** [comment]
> Can someone provide a zip of a test site so we can try to reproduce this?

I believe this is already fixed in [this](https://github.com/schnumsel/grav-plugin-tntsearch/commit/558b76352a1a5fa802682291bfc56176f4a71fb7) commit, but a new release hasn't been prepared yet. The fix is discussed in #107 

Manually changing that file with that change fixes the tnt-search queries instantly.

**Comment by rhukster** [comment]
I will investigate this and get a release out.

**Comment by rhukster** [comment]
Please try again with 3.3.1 (when it shows up in GPM)

**Comment by AquaL1te** [comment]
> Please try again with 3.3.1 (when it shows up in GPM)

It still works here after updating the plugin. Perhaps @jraack can give it a go as well?

**Comment by jraack** [comment]
Hi, Thanks for your replies.

I have updated tntsearch, on Docker i dont get results, on a local test, running via php -S it works after re-indexing.
Is there an additional config needed for docker to run tntsearch? Maybe writes access?

**Comment by jraack** [comment]
I still don't get results when i run the grav instance and plugin tntsearch on the Docker Image. Any ideas? In docker i get a completed indexing. Really weird.

**Comment by jraack** [comment]
@rhukster Nevermind this issue. It was not installing the tntsearch plugin, and i was indexing before it was completed.
So it has been fixed.

**Comment by jraack** [comment]
unfortunately when i try to re-index it gives me an error
Invalid resource theme://

Any suggestions?

**Comment by rhukster** [comment]
What version of Grav / TNTSearch and PHP?

**Comment by jraack** [comment]
PHP7.4, TNTSearch latest 3.3.1

**Comment by darrenhollick** [comment]
I'm still having this issue.
Grav 1.7.38
TNTSearch 3.3.1
PHP 7.4.13 (IIS)
